### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by RasmusKlett** [django-blog-zinnia/zinnia-spam-checker-akismet#1]
The zinnia_akismet.akismet tries to do "from akismet import Akismet". It seems it expects this "akismet" to refer to the akismet module it depends on, but it seems to instead resolve to itself, since it has the same name. At least on my setup which is:
Django 1.6
Python 2.7.8
Zinnia 0.14.3
Running in virtualenv

**Comment by Fantomas42** [comment]
Ok I will try to reproduce.

**Comment by Fantomas42** [comment]
The release v1.1 resolve the issue.
